spring.application.name=lenguajesP3

#puerto
server.address=0.0.0.0
server.port=${PORT:8080}

# Configuración de la Base de Datos (Local)
spring.datasource.url=jdbc:postgresql://localhost:5432/db_restaurant
spring.datasource.username=postgres
spring.datasource.password=6509
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.hibernate.SQL=debug

