spring.application.name=lenguajesP3

#puerto
server.address=0.0.0.0
server.port=${PORT:8080}

# Configuración de la Base de Datos (PostgreSQL)
# Configuración de la Base de Datos (PostgreSQL - Render)
spring.datasource.url=jdbc:postgresql://dpg-d8473h09rddc739d17q0-a.oregon-postgres.render.com:5432/db_restaurant_ip40?sslmode=require
spring.datasource.username=db_restaurant_ip40_user
# IMPORTANTE: Poné acá el password que sacás del dashboard de la DB en Render:
spring.datasource.password=PONER_AQUI_TU_PASSWORD_DE_RENDER
spring.datasource.driver-class-name=org.postgresql.Driver

# Forzar SSL para que Render no nos corte la conexión
spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.hibernate.SQL=debug

